### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by WirelessMind** [s60sc/ESP32_VoiceChanger#2]
it is not an issue, but a request.  Do you have the schematic you used? Can you share it?

**Comment by WirelessMind** [comment]
but I don't undestand.
myConfig.h doesn't exist.

I see in appGlobals.h:
```
// MAX9814 ADC microphone pinout, Gain & AR can be left disconnected
#ifdef CONFIG_IDF_TARGET_ESP32
#define I2S_ADC_UNIT    ADC_UNIT_1
#define I2S_ADC_CHANNEL ADC1_CHANNEL_5 // Out pin GPIO37
#endif

// ICSK025A DAC amplifier (LM386)
// use right channel 
#ifdef CONFIG_IDF_TARGET_ESP32
#define I2S_DAC_CHANNEL I2S_DAC_CHANNEL_RIGHT_EN // GPIO25 (J5+ pin)
#endif
```

I have INMP441 I2S microphone and MAX98357A I2S 3W amplifier, but I don't know how I have to link with my ESP32 devkit:
![VoiceChangerESP32](https://user-images.githubusercontent.com/18408814/226073598-2167df19-179f-4170-8baa-ae7544cd1135.png)

**Comment by s60sc** [comment]
This guy has some esp32 audio vids that may lelp
`https://www.youtube.com/channel/UC4Otk-uDioJN0tg6s1QO9lw`
