### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by girs1982** [s60sc/ESP32_VoiceChanger#5]
![image](https://user-images.githubusercontent.com/13913400/235744522-58eb0106-e8df-49a5-8e39-cf30c0fac763.png)
hello,
some shit , i try run with i2s mic ,but now

**Comment by s60sc** [comment]
![Screenshot 2023-05-02 185750](https://user-images.githubusercontent.com/23615220/235755547-0dfc4138-bfb6-46e8-bb0b-6e49002a818c.png)

**Comment by girs1982** [comment]
> ![Screenshot 2023-05-02 185750](https://user-images.githubusercontent.com/23615220/235755547-0dfc4138-bfb6-46e8-bb0b-6e49002a818c.png)

amplifer not i2s , what the pins need?

**Comment by girs1982** [comment]
![image](https://user-images.githubusercontent.com/13913400/235768235-3f015e5f-3700-4f36-80fb-317212e411b0.png)
[00:05:39.250 getLocalNTP] Using NTP server: pool.ntp.org
[00:05:39.251 WARN getLocalNTP] Not yet synced with NTP 
E (40778) I2S: i2s_adc_disable(1391): Not initialized yet
E (40778) I2S: i2s_adc_disable(1391): Not initialized yet
E (40778) I2S: i2s_driver_uninstall(2047): I2S port 0 has not installed
E (40783) I2S: i2s_driver_uninstall(2047): I2S port 1 has not installed

**Comment by s60sc** [comment]
Use pin 25 for analog amp

Log shows that mic has been setup

**Comment by girs1982** [comment]
pin numbers? for all?

**Comment by girs1982** [comment]
![image](https://user-images.githubusercontent.com/13913400/235781253-2be0295d-5708-4f0a-8a77-3b15724bbd64.png)

**Comment by girs1982** [comment]
no work
